[project]
name = "pydantic-ai-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire>=3.19.0",
    "pydantic-ai>=0.2.18",
    "python-dotenv>=1.1.0",
]
